DEFINES+=PROJECT_CONF_H=\"project-conf.h\"
CONTIKI_PROJECT = gather
all: $(CONTIKI_PROJECT)

CONTIKI_TARGET_SOURCEFILES += gather_msg.c

#UIP_CONF_IPV6=1

CONTIKI = ../..



include $(CONTIKI)/Makefile.include
